### ISSUE TITLE
Voltage, current and temperature calibration

### ISSUE THREAD

**Issue by ss8688** [am32-firmware/AM32#14]
The voltage on my Crawler ESC is inaccurate with a voltage deviation of -0.7V. Which means when cut off is 350 it cut off at 2.8v.It is  dangerously low for lipo battery.

Hope there is a function display current voltage and allow to calibrate.Also for current and temperature

**Comment by AlkaMotors** [comment]
Calibration is not required on voltage dividers. The resistors are fixed values and their accuracy is +-1 percent. You left out the important details.. What ESC you have and what firmware is flashed to it. The issue is normally that a firmware meant for another esc is flashed.. which of course will give incorrect values for any other esc except the one it was made for. If you bought the esc from a manufacturer pre-flashed they should contact us to make a target that matches their schematic.
